# Generated by Django 2.0.13 on 2019-05-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190527_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='view_count',
        ),
    ]
