# Generated by Django 2.0.13 on 2019-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20190528_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_written',
            field=models.BooleanField(default=False),
        ),
    ]
